#!/usr/bin/python

from bs4 import BeautifulSoup
import requests
from argparse import ArgumentParser
import math

BASEURL = "http://na.finalfantasyxiv.com"

def print_items(soup):
    """Grabs a soup, expecting a character page, and prints the item
       level sheet of said page."""
    names = []
    levels = []
    weapon = soup.find("p", class_="db-tooltip__item__category").string
    job = weapon.split("'")[0] #We need to know what job the player is

    for item in soup.find_all("h2", class_="db-tooltip__item__name"):
        names.append(str(item.contents[0])) #lists all item names
                                            #sometimes this contains
                                            #an <img>, so .string wont work

    for level in soup.find_all("div", class_="db-tooltip__item__level"):
        levels.append(int(level.string.split()[2])) #lists all item levels
    
    items = list(zip(names, levels)) #list(zip()) returns list(tuple)
    items = items[int(len(items) / 2):] #every item appears twice in soup
                                        #so we cut the list in half

    if (items[-1][0].startswith("Soul of the ")):
            items = items[:-1] #and we dont care for eventual souls
    pad = max(len(s[0]) for s in items) #find the longest item name
                                        #and store the length
    if (job == "Paladin"):
        total = 0 
    else:
        total = items[0][1] #for any non-paladin, weapon counts twice

    for item in items:
        print(item[0].ljust(pad) + " | " + str(item[1]))
        total += item[1]

    print(" " * (pad + 3), end='') #left-pad the average item level
    if (job == "Paladin"):
        print(math.floor(total / (len(items)))) #paladin
    else:
        print(math.floor(total / (len(items) + 1))) #non-paladin

if __name__ == "__main__":
    parser = ArgumentParser(description='Post FFXIV Lodestone stats')
    parser.add_argument('name', nargs='*', help="Character name")
    parser.add_argument('-w', '--world', default="", help='World')
    args = parser.parse_args()

    name = "+".join(args.name[0:2])
    world = args.world.capitalize()
    
    r = requests.get(BASEURL
                     + "/lodestone/character/?q="
                     + name
                     + "&worldname="
                     + world)
    soup = BeautifulSoup(r.text, "html.parser")
    chars = []
    for h4 in soup.find_all("h4", class_="player_name_gold"):
        href = h4.a.get("href") #get is required because href isnt a child
        string = h4.a.string
        chars.append((string, href)) #tuple!

    for char in chars:
        if(char[0] == " ".join(name.split("+")).title()):
            r = requests.get(BASEURL + char[1])
            break #only get the first result, obviously
    
    soup = BeautifulSoup(r.text, "html.parser")
    print(" ".join(name.split("+")).title())
    print(" ")
    print_items(soup)
